version: "1.0"
services:
  postgres:
    container_name: "CW"
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "Maxim"
      POSTGRES_PASSWORD: "12345"
    volumes:
      #- ./mapped:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  redis_data: